services:
  api:
    container_name: api
    build:
      context: api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - MODEL_SERVER_URL=http://seq_model_server:3000
      - FEAST_ONLINE_SERVER_HOST=feature_online_server
    volumes:
      - ./api:/app/api
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - recsys

  seq_model_server:
    container_name: seq_model_server
    build:
      context: .
      dockerfile: model_server.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
    entrypoint: ["bentoml", "serve", "service:SeqRPService"]
    networks:
      - recsys

networks:
  recsys:
    external: true
